name = "clang-arm-plugin"
description = "clang 11.0.0 for arm"
version = "11.0.0" 
	
[packaging]
	include = [
		"cmake",
		"include",
		"clang_arm_plugin",
		"template",
		"clang",
		"gcc",
		"__init__.py"
	]
	exclude = [
		"*.pyc"
	]