#!/bin/bash

xpl_path=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

cd ${xpl_path}/..

set -e

if [ ! -d clang/bin ]
then
	rm -rf clang
	
	clang_url=https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
	curl $clang_url -L --progress-bar -o clang-arm.tar.xz
	
	tar -xvf clang-arm.tar.xz
	mv clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-16.04 clang
	rm clang-arm.tar.xz
fi

if [ ! -d gcc/arm-none-eabi ]
then
	rm -rf gcc
	
	gcc_url=https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
	curl $gcc_url -L --progress-bar -o gcc-arm-none-eabi.tar.bz2
	
	tar -xvf gcc-arm-none-eabi.tar.bz2
	mv gcc-arm-none-eabi-9-2020-q2-update gcc
	rm gcc-arm-none-eabi.tar.bz2
fi

# https://interrupt.memfault.com/blog/arm-cortexm-with-llvm-clang
if [ ! -d compiler-rt ]
then
	compiler_rt_url=https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/compiler-rt-11.0.0.src.tar.xz
	curl $compiler_rt_url -L --progress-bar -o compiler-rt.tar.xz
	
	tar -xvf compiler-rt.tar.xz
	mv compiler-rt-11.0.0.src compiler-rt
	rm compiler-rt.tar.xz
fi

